-- Tabela de placares (ver app/types/database.types.ts e app/services/placar.ts)
create table public."Placar" (
	id bigint generated by default as identity primary key,
	created_at timestamptz not null default now(),
	creator uuid not null references auth.users (id) on delete cascade,
	public_id text not null unique,
	score_increment integer not null default 1,
	team_a_name text not null default '',
	team_a_score integer default 0,
	team_b_name text not null default '',
	team_b_score integer default 0
);

create index "Placar_creator_idx" on public."Placar" (creator);

alter table public."Placar" enable row level security;

-- Qualquer pessoa pode ver um placar (a página /id/[id] é pública)
create policy "Placares são públicos para leitura"
	on public."Placar" for select
	to anon, authenticated
	using (true);

-- Somente usuários logados criam placares, sempre em seu próprio nome
create policy "Usuários criam os próprios placares"
	on public."Placar" for insert
	to authenticated
	with check ((select auth.uid()) = creator);

-- Somente o criador altera o placar (pontuação e reinício)
create policy "Criador atualiza o próprio placar"
	on public."Placar" for update
	to authenticated
	using ((select auth.uid()) = creator)
	with check ((select auth.uid()) = creator);

-- Somente o criador apaga o placar
create policy "Criador apaga o próprio placar"
	on public."Placar" for delete
	to authenticated
	using ((select auth.uid()) = creator);
