-- Redesign (docs/placar-design/HANDOFF.md, seção 3): cores dos times, tamanho dos números,
-- travas de pontuação, histórico de jogadas e funções para pontuar, desfazer e reiniciar.

-- ============================================================
-- Placar: colunas novas
-- ============================================================

alter table public."Placar"
	add column team_a_color text not null default '#51a2ff',
	add column team_b_color text not null default '#ff8904',
	add column score_size text not null default 'G';

-- Ajusta dados antigos que ficariam fora das regras abaixo
update public."Placar"
set
	team_a_score = greatest(coalesce(team_a_score, 0), 0),
	team_b_score = greatest(coalesce(team_b_score, 0), 0),
	score_increment = greatest(score_increment, 1),
	team_a_name = coalesce(nullif(left(btrim(team_a_name), 24), ''), 'Time 1'),
	team_b_name = coalesce(nullif(left(btrim(team_b_name), 24), ''), 'Time 2');

alter table public."Placar"
	add constraint "Placar_team_a_color_check" check (team_a_color ~ '^#[0-9a-f]{6}$'),
	add constraint "Placar_team_b_color_check" check (team_b_color ~ '^#[0-9a-f]{6}$'),
	add constraint "Placar_score_size_check" check (score_size in ('P', 'M', 'G')),
	add constraint "Placar_team_a_score_check" check (team_a_score >= 0),
	add constraint "Placar_team_b_score_check" check (team_b_score >= 0),
	add constraint "Placar_score_increment_check" check (score_increment >= 1),
	add constraint "Placar_team_a_name_check" check (char_length(team_a_name) between 1 and 24),
	add constraint "Placar_team_b_name_check" check (char_length(team_b_name) between 1 and 24);

-- ============================================================
-- PlacarEvent: histórico de jogadas ("Últimas jogadas" e "Desfazer")
-- ============================================================

create table public."PlacarEvent" (
	id bigint generated by default as identity primary key,
	placar_id bigint not null references public."Placar" (id) on delete cascade,
	team text not null check (team in ('a', 'b')),
	delta integer not null check (delta <> 0),
	score_after integer not null check (score_after >= 0),
	created_at timestamptz not null default now()
);

create index "PlacarEvent_placar_id_created_at_idx" on public."PlacarEvent" (placar_id, created_at desc, id desc);

alter table public."PlacarEvent" enable row level security;

-- Quem vê o placar vê as jogadas (a página /id/[id] é pública)
create policy "Jogadas são públicas para leitura"
	on public."PlacarEvent" for select
	to anon, authenticated
	using (true);

-- Só o criador do placar registra e apaga jogadas
create policy "Criador registra jogadas"
	on public."PlacarEvent" for insert
	to authenticated
	with check (
		exists (
			select 1 from public."Placar" p
			where p.id = placar_id and p.creator = (select auth.uid())
		)
	);

create policy "Criador apaga jogadas"
	on public."PlacarEvent" for delete
	to authenticated
	using (
		exists (
			select 1 from public."Placar" p
			where p.id = placar_id and p.creator = (select auth.uid())
		)
	);

-- ============================================================
-- Funções (RPC)
-- Rodam com as permissões de quem chama (security invoker), então a RLS continua valendo:
-- para quem não é o criador, o update não encontra a linha e a função falha.
-- ============================================================

-- Soma ou subtrai o incremento numa única operação (sem perder ponto com cliques simultâneos),
-- sem deixar a pontuação ficar abaixo de 0, e registra a jogada.
-- Retorna a pontuação nova do time.
create function public.placar_add_points(p_public_id text, p_team text, p_direction text)
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_placar_id bigint;
	v_before integer;
	v_after integer;
begin
	if p_team not in ('a', 'b') then
		raise exception 'Time inválido: %', p_team using errcode = '22023';
	end if;
	if p_direction not in ('increment', 'decrement') then
		raise exception 'Direção inválida: %', p_direction using errcode = '22023';
	end if;

	-- O "for update" trava a linha até o fim da transação: cliques simultâneos entram em fila
	select id, case when p_team = 'a' then coalesce(team_a_score, 0) else coalesce(team_b_score, 0) end
	into v_placar_id, v_before
	from public."Placar"
	where public_id = p_public_id
	for update;

	if v_placar_id is null then
		raise exception 'Placar não encontrado' using errcode = 'P0002';
	end if;

	v_after := greatest(
		0,
		v_before + (
			select case when p_direction = 'increment' then score_increment else -score_increment end
			from public."Placar"
			where id = v_placar_id
		)
	);

	-- Time já em 0 e clique para tirar: nada muda, nada é registrado
	if v_after = v_before then
		return v_before;
	end if;

	if p_team = 'a' then
		update public."Placar" set team_a_score = v_after where id = v_placar_id;
	else
		update public."Placar" set team_b_score = v_after where id = v_placar_id;
	end if;

	if not found then
		raise exception 'Sem permissão para alterar este placar' using errcode = '42501';
	end if;

	insert into public."PlacarEvent" (placar_id, team, delta, score_after)
	values (v_placar_id, p_team, v_after - v_before, v_after);

	return v_after;
end;
$$;

-- Desfaz a última jogada: aplica o inverso e apaga o registro.
-- Retorna a jogada desfeita, ou nenhuma linha se não houver jogadas.
create function public.placar_undo_last(p_public_id text)
returns table (team text, score integer)
language plpgsql
security invoker
set search_path = ''
as $$
#variable_conflict use_column
declare
	v_placar_id bigint;
	v_event public."PlacarEvent";
	v_score integer;
begin
	select id into v_placar_id
	from public."Placar"
	where public_id = p_public_id
	for update;

	if v_placar_id is null then
		raise exception 'Placar não encontrado' using errcode = 'P0002';
	end if;

	select * into v_event
	from public."PlacarEvent"
	where placar_id = v_placar_id
	order by created_at desc, id desc
	limit 1;

	if v_event.id is null then
		return;
	end if;

	if v_event.team = 'a' then
		update public."Placar" set team_a_score = greatest(0, coalesce(team_a_score, 0) - v_event.delta)
		where id = v_placar_id
		returning team_a_score into v_score;
	else
		update public."Placar" set team_b_score = greatest(0, coalesce(team_b_score, 0) - v_event.delta)
		where id = v_placar_id
		returning team_b_score into v_score;
	end if;

	if not found then
		raise exception 'Sem permissão para alterar este placar' using errcode = '42501';
	end if;

	delete from public."PlacarEvent" where id = v_event.id;

	team := v_event.team;
	score := v_score;
	return next;
end;
$$;

-- Reinicia a partida: zera as duas pontuações e apaga as jogadas, na mesma transação
create function public.placar_reset(p_public_id text)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_placar_id bigint;
begin
	update public."Placar"
	set team_a_score = 0, team_b_score = 0
	where public_id = p_public_id
	returning id into v_placar_id;

	if v_placar_id is null then
		raise exception 'Placar não encontrado' using errcode = 'P0002';
	end if;

	delete from public."PlacarEvent" where placar_id = v_placar_id;
end;
$$;

revoke execute on function public.placar_add_points(text, text, text) from public, anon;
revoke execute on function public.placar_undo_last(text) from public, anon;
revoke execute on function public.placar_reset(text) from public, anon;

grant execute on function public.placar_add_points(text, text, text) to authenticated;
grant execute on function public.placar_undo_last(text) to authenticated;
grant execute on function public.placar_reset(text) to authenticated;
